### ISSUE TITLE
[BUG] Non-global scope leaks caller

### ISSUE THREAD

**Issue by elizrus** [dropbox/Store#197] opened 2020-08-03 22:10 UTC
**Describe the bug**
Disclaimer: I'm no expert in coroutine scoping, so there's a great chance this is user error.  
When I build a Store and declare a Scope that is not GlobalScope, I found that calling fetch on Store will leak my caller.  

**To Reproduce**
Here's a minimal activity that reproduces the issue.  On config change (screen rotation), MainActivity is retained--- forever as far as I can tell. If I omit the scope argument on the Store builder or set the scope to global, I get the behavior I expect, which is that the fetch is cancelled and no scope is retained.  

I tried following the ref chain down- it seems the scope assigned to FetcherController (which is the scope I passed into the builder) is ultimately retaining my Activity.  

```kotlin
class MainActivity : AppCompatActivity() {
    var time: Long = 0
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        time = System.currentTimeMillis()

        lifecycleScope.launch {
            store.fresh(time)
        }
    }
}

object Repository {
    val store = StoreBuilder.from(
        fetcher = nonFlowFetcher<Long, Long> {
            delay(5000)
            FetcherResult.Data(it)        }
    ).scope(CoroutineScope(Dispatchers.Main)).build()
}
```

**Expected behavior**
My expectation is that when I cancel the scope around my Store call (store.fresh()), I'd see a cancellation of any child jobs or Flows that Store has spawned for me, and I would not be retained by Store's scope.

** Additional context**
Here's a heap dump!
[heap_dump_several_main_activities.txt](https://github.com/dropbox/Store/files/5018987/heap_dump_several_main_activities.txt)

**Comment by zach-klippenstein** [comment] 2020-08-04 18:33
I think I found the leak, or at least one of the areas that's leaking.

Here's a screenshot of a heapdump analysis: 
![image](https://user-images.githubusercontent.com/101754/89327674-20384b80-d641-11ea-8b41-de987f75666c.png)

The `onEach in ChannelManager` looked suspicious to me, and digging through the source I found that `onEach` is passed a lambda from the `RefCountedResource.create` lambda passed by `FetcherController`'s initializer:
https://github.com/dropbox/Store/blob/b86050496cc10b78a26ef2549551404f820eb407/store/src/main/java/com/dropbox/android/external/store4/impl/FetcherController.kt#L64-L92

The create function call hierarchy that invokes it is:
1. `Store.fresh` calls `RealStore.stream` which returns a flow, and then it uses the current coroutine context (it's a suspend function) to call `first()`, which collects the flow in the current context.
1. `RealStore.stream` creates a `Flow` which, when collected, calls `createNetworkFlow`.
1. `createNetworkFlow` returns a flow by calling `fetcherController.getFetcher()`.
1. `fetcherController.getFetcher()` creates a `Flow` which, when collected, calls `fetchers.acquire()`. `fetchers` is that `RefCountedResource`.
1. `RefCountedResource.acquire()` invokes the `create` parameter passed to its constructor in the current coroutine context:
https://github.com/dropbox/Store/blob/d733da166275e846921445c22eb3877d285ed068/store/src/main/java/com/dropbox/android/external/store4/impl/RefCountedResource.kt#L31-L37
The `create` parameter to `RefCountedResource` is a suspend function, and that's interesting since the lambda passed in by `FetcherController` doesn't make any suspend calls.
1. The `create` lambda creates a `Multicaster` and passes a lambda to its `onEach` parameter. 
1. `Multicaster`'s creates and stores a `ChannelManager` in a field, and passes the `onEach` argument to it.
1. `ChannelManager` calls `onEach` from `doDispatchValue`, which is called from an `actor` coroutine launched by the `StoreRealActor` class.

To summarize: When `Store.fresh` is called, it indirectly launches a coroutine in the `StoreBuilder.scope` `CoroutineScope` that captures a lambda to call on every emitted value. This lambda is created by the lambda that `FetcherController` passes to `RefCountedResource`'s constructor as the `create` function. `RefCountedResource.create` eventually gets called in the coroutine context of the `Store.fresh` call.

https://github.com/dropbox/Store/blob/b86050496cc10b78a26ef2549551404f820eb407/store/src/main/java/com/dropbox/android/external/store4/impl/FetcherController.kt#L86-L90

Here's one potential problem: When the `create` lambda passes a lambda to `onEach`, the `onEach` lambda ends up capturing the `coroutineContext` from the `create` call. If you put a debug breakpoint in the `onEach` lambda (line 87) and inspect variables, you'll see that the `onEach.this` captures `create.this` (`this$0`) which has a `_context` field that references the coroutine context passed to `Store.fresh`. This context is created by `lifecycleScope`, which captures the `Activity`, and so it's leaked as long as the `onEach` lambda is referenced by something (in this case, the coroutine that is started in the `StoreBuilder.scope`). **I think this problem can be fixed by simply making the `create` parameter non-suspending`, since it doesn't need to be suspending anyway.**

![image](https://user-images.githubusercontent.com/101754/89329679-fcc2d000-d643-11ea-9774-b2f51c47e3f2.png)

It seems like this should be fine, since the coroutine started by the `Multicaster` should be cancelled, and the reference to the `Multicaster` released, when the `fetchers.release` call is made after emitting the first response. However, the heap dump shows that the `StoreBuilder.scope` jobs holds a reference to a child continuation which has a reference to the caller frame for debug purposes, and that frame has a reference to the `onEach` lambda. I'm not sure why this child continuation isn't being released, but that seems like a coroutine bug.

Sorry for the rambling explanation, I think there are a few bugs here. One is that the `coroutineContext` from the `create` lambda is being captured unnecessarily by the `onEach` lambda. This library can workaround that by making `create` non-suspending. The other bug is that a child continuation with a reference to that context is being held onto by the coroutines machinery after being cancelled.

**Comment by eyalgu** [comment] 2020-08-05 01:08
Thanks for the A+ analysis @zach-klippenstein! 
interestingly enough when running the above repro I don't get a memory leak (main activity is destroyed) and I don't see a reference to `create` saved in `onEach` which may indicate a difference between Kotlin std versions or something of the sort. what kotlin version are you running against?

![Screen Shot 2020-08-04 at 6 06 48 PM](https://user-images.githubusercontent.com/1657897/89360463-68755f00-d67d-11ea-85c2-d708d5ea44a2.png)

The other alternative is that some of the changes made post alpha06 fixed this (though I doubt it).

**Comment by elizrus** [comment] 2020-08-05 14:15
Kotlin 1.3.72.  
I did just reproduce by replacing the sample with my activity on the main branch of Store. Further, I verified that removing the suspend modifier fixes the leak.

**Comment by steve-the-edwards** [comment] 2020-08-05 14:33
Yup, also can reproduce in the sample app by adding this on line 60 in RoomFragment

```
lifecycleScope.launchWhenStarted {
            storeState.store.fresh("aww")
```

**Comment by zach-klippenstein** [comment] 2020-08-05 15:28
We are also seeing the activity get destroyed, but it's never garbage collected.

**Comment by eyalgu** [comment] 2020-08-05 15:58
> Kotlin 1.3.72.
> I did just reproduce by replacing the sample with my activity on the main branch of Store. Further, I verified that removing the suspend modifier from the create lambda in RefCountedResource fixes the leak.

Wanna send a PR?

**Comment by digitalbuddha** [comment] 2020-08-05 16:38
Thank you so much for finding/fixing

**Comment by eyalgu** [comment] 2020-08-05 16:38
Actually a better solution would be to break the chain between onEach and create. I'll throw up an altenate pr

**Comment by eyalgu** [comment] 2020-08-05 16:49
full solution:
1) call `fetchers.acquire` on the store's `scope` to avoid capturing `stream`'s scope in the multicaster where it will be preserved (by design)
2) for added safety, prevent `onEach` from capturing a reference to `create` as it actually does not need it

**Comment by eyalgu** [comment] 2020-08-05 16:54
actually, I'm just going to do (1). (2) isn't a problem if `create` has the right scope

**Comment by zach-klippenstein** [comment] 2020-08-05 17:10
Suspend functions aren't free though, it's generally better to not define a function as `suspend` unless it actually needs to make a suspend call at some point.

**Comment by eyalgu** [comment] 2020-08-05 17:17
> Suspend functions aren't free though, it's generally better to not define a function as `suspend` unless it actually needs to make a suspend call at some point.

True, but in this case `RefCountedResource`'s API makes sense as a suspend API (even though in this specific case it's not). Even if I remove suspend from `create` to fix this it's very possible that someone will need to add it back in the future and thus will re-introduce this leak

**Comment by zach-klippenstein** [comment] 2020-08-05 17:35
> it's very possible that someone will need to add it back in the future

This seems like a smell to me. If it needs to be suspend in the future, it could be made suspend. But without a specific use case, this seems like just making the code more complex for no reason, which is generally a practice that should be avoided (introduces maintenance burdens like this, and is similar to premature abstraction or premature optimization).

Anyway, this isn't my code, up to you! 😅 Thanks for taking a look at this and finding the more fundamental issue!

**Comment by eyalgu** [comment] 2020-08-05 18:12
> this seems like just making the code more complex for no reason
I don't think I agree, `create` could very naturally be a suspend function (given how generic `RefCountedResource`'s API is). If we just remove it it's not unlikely to come back in the future when someone, unaware of this discussion changes it back because it needs it now to be suspend.

**Closed** 2020-08-05 22:37 UTC
Labels: bug
