### ISSUE TITLE
Compatibility issue with Kotlin 1.6

### ISSUE THREAD

**Issue by bishiboosh** [dropbox/Store#339] opened 2021-11-17 09:43 UTC
**Describe the bug**
Duration API has been made stable in Kotlin 1.6.0, and some methods have been deleted. As result, the following error appears:

```
java.lang.NoSuchMethodError: No static method toDuration(DLjava/util/concurrent/TimeUnit;)J in class Lkotlin/time/DurationKt; or its super classes (declaration of 'kotlin.time.DurationKt' appears in /data/app/com.enki.Enki750g-dL2OkPW0zzwa1CQrnIAsnQ==/base.apk!classes22.dex)
        at com.dropbox.android.external.store4.MemoryPolicy.<clinit>(MemoryPolicy.kt:116)
        at com.dropbox.android.external.store4.StoreDefaults.<clinit>(StoreDefaults.kt:23)
        at com.dropbox.android.external.store4.RealStoreBuilder.<init>(StoreBuilder.kt:91)
        at com.dropbox.android.external.store4.StoreBuilder$Companion.from(StoreBuilder.kt:76)
        at com.webedia.food.config.ConfigManager.<init>(ConfigManager.kt:51)
```

**To Reproduce**

Create a store with the default options.

**Expected behavior**
Should not crash

**Infos**
 - Store Version: 4.0.2-KT15

**Comment by bishiboosh** [comment] 2021-11-17 09:44
A release requiring Kotlin 1.6.0 (and fixing the deleted methods) should probably be done now that the Duration API is stable, and hopefully there won't be any more problems then :)

**Comment by digitalbuddha** [comment] 2021-11-17 13:08
Got it. I’ll make a new version today. I didn’t realize it was another compat problem and not same as last one.

**Comment by bishiboosh** [comment] 2021-11-17 16:57
I don't know when 1.6.0 will be widely used, so a -kt16 version may be the right solution to avoid the same issues you had with 1.5 last time :/

**Comment by argenkiwi** [comment] 2021-11-17 19:47
So these issues occur because the Store library uses experimental APIs?

**Comment by digitalbuddha** [comment] 2021-11-17 19:49
Yeah this was a mistake I made, we wanted to ease into kotlin multi platform and didn’t realize this was an unstable api.

**Comment by bishiboosh** [comment] 2021-11-17 20:06
Duration API has been a PITA for a couple of libs, I know it was marked as experimental but I wish the API surface hadn't moved that much during development

**Comment by digitalbuddha** [comment] 2021-11-18 19:09
Hi folks, store has modules that depend on Moshi, we are unable to upgrade Store to 1.6 until Moshi metadata issues are resolved 
Caused by: java.lang.IllegalStateException: Could not parse metadata! This should only happen if you're using Kotlin <1.1.
        at com.squareup.moshi.kotlinpoet.metadata.KotlinPoetMetadata.readKotlinClassMetadata(KotlinPoetMetadata.kt:89)

Will keep this open for now

**Comment by mirland** [comment] 2021-11-19 15:57
@digitalbuddha Moshi is a third-party library, in my opinion, we should migrate it to [Kotlin Serialization Library](https://kotlinlang.org/docs/serialization.html). You will avoid this kind of issue. Furthermore, it's used only in the sample app, so the migration shouldn't be hard. thought?

**Comment by julioromano** [comment] 2021-12-02 08:25
Switching to MoshiX + Ksp also solves the Kotlin 1.6 compatibility issue and usually requires just a trivial dependency change: https://github.com/ZacSweers/MoshiX/tree/main/moshi-ksp

Otherwise, MoshiX has already been merged in Moshi's master so hopefully a new Moshi version (therefore compatible with Kotlin 1.6) should soon land.

**Comment by julioromano** [comment] 2021-12-02 08:40
Turns out, in case of need, this issue can be monkey patched adding this function in the module that fails to compile:
```
package kotlin.time

import java.util.concurrent.TimeUnit

@OptIn(ExperimentalTime::class)
public fun Double.toDuration(unit: TimeUnit): Duration = toDuration(unit.toDurationUnit())
```

Also don't forget to add the following to the module's `build.gradle` (hereafter in Kotlin DSL syntax) :
```
tasks.withType<KotlinCompile> {
  kotlinOptions {
    freeCompilerArgs += "-Xallow-kotlin-package"
  }
}
``` 
Hope this helps.

**Comment by natario1** [comment] 2021-12-02 16:59
It is very strange that we can't compile a library that is so popular on the last major version, and even for 1.5 one has to use a different artifact which sounds like a workaround (even if it isn't). And this is just because the sample app depends on moshi? 

Can you create a 1.6 branch where the sample app is removed, then add it back once moshi fixes their stuff? Which, by the way, was already done 9 days ago - https://github.com/square/moshi/pull/1431 . So another option is to have the sample app depend on moshi's snapshots.

**Comment by digitalbuddha** [comment] 2021-12-03 12:52
1.5 issue is not moshi but a time api we depend on.  1.6 overall has been a bit of a weird situation as it broke incremental compilation for us and most other apps. It did not feel safe to make that the main version. Maintaining 3 versions would be a stretch too. Thanks for the moshi link I’ll keep an eye on it through the weekend. I’ll change to snapshot and release at some point next week.

**Comment by mirland** [comment] 2021-12-03 14:13
Duration [api is stable in 1.6](https://blog.jetbrains.com/kotlin/2021/11/kotlin-1-6-0-is-released/#standard-library), so you shouldn't have that problem in the future. 

>  Maintaining 3 versions would be a stretch too.
I see your point but, Kotlin 1.4 is too old, so I think it shouldn't be Maintaining. 

BTW: couldn't we remove Moshi? I mean, Jetbrains libraries should give less problem in the upgrades

**Closed** 2021-12-07 14:52 UTC
Labels: bug

**Comment by digitalbuddha** [comment] 2021-12-07 15:22
The moshi integration was a bit of an integration test. We are using moshi internally. There should be a snapshot up with a fix now/soon

**Comment by mirland** [comment] 2021-12-07 15:49
> The moshi integration was a bit of an integration test. We are using moshi internally. There should be a snapshot up with a fix now/soon

Hi @digitalbuddha, I see your point. However, I think if they release a new version, you can have this type of issue in the future. If you use the "official" library, you will avoid a lot of issues.

I think moshi is ok, If you prefer to use it as a serialization layer in the sample app, [just comment it in my pr](https://github.com/dropbox/Store/pull/355) and close it!

thanks!

**Comment by digitalbuddha** [comment] 2021-12-07 16:05
Thank you for the pr let me discuss internally. Your thinking makes sense
